### ISSUE TITLE
No hay estadísticas.

### ISSUE THREAD

**Issue by driosalido** [yinyang17/pvpc_energy#15]
Buenos días.

Estos son los datos de los componentes.
pvcp_energy version 0.2.3
Home Assistant Version 2024.7.4

Al instalar la integración puedo ver como se recolectan los datos correctamente. En el directorio `/root/config/custom_components/pvpc_energy/user_files` aparecen tanto el billing_periods.csv y el energy_data.csv con datos a priori correctos.

Puedo generar el informe de las facturas correctamente pero las estadísticas no aparecen accesibles. No puedo importar los datos en el dashboard de energía ni puedo ver ninguna otra estadística en la sección de herramientas para desarolladores/estadisticas.

He habilitado el debug de la integración y puedo ver todas las peticiones de consulta de datos externas correctas. El único warning que veo es el siguiente

```
2024-08-02 09:55:35.845 DEBUG (MainThread) [custom_components.pvpc_energy.coordinator] START - save_billing_periods(file_path=/config/custom_components/pvpc_energy/user_files/billing_periods.csv, len(billing_periods)=27)
2024-08-02 09:55:35.852 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/pvpc_energy/user_files/billing_periods.csv', 'w') inside the event loop by custom integration 'pvpc_energy' at custom_components/pvpc_energy/coordinator.py, line 336: with open(file_path, 'w') as file: (offender: /config/custom_components/pvpc_energy/coordinator.py, line 336: with open(file_path, 'w') as file:), please create a bug report at https://github.com/yinyang17/pvpc_energy/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/pvpc_energy/coordinator.py", line 144, in import_energy_data
    await PvpcCoordinator.calculate_bills(billing_periods, consumptions, hass, force_update)
  File "/config/custom_components/pvpc_energy/coordinator.py", line 222, in calculate_bills
    PvpcCoordinator.save_billing_periods(BILLING_PERIODS_FILE, billing_periods)
  File "/config/custom_components/pvpc_energy/coordinator.py", line 336, in save_billing_periods
    with open(file_path, 'w') as file:
    ```
    
    Alguna idea de que puede estar pasando o alguna otra idea de poder depurar donde se estan quedan las estadísticas?

**Comment by neoalarrode** [comment]
Hola, 
por lo que te estoy entendiendo el problema es que no te aparecen las entidades para añadir en la configuración del dashboard de Energía, ten en cuenta que desde que se generan las entidades puede pasar varias horas hasta ha HA, normalmente suele ser a la vez que se procesan e integran los datos en la entidad, esto también puede depender de la velocidad y la capacidad de procesamiento que tenga la máquina en la que ejecutas HA, de igual forma puedes probar a llamar al servicio de UFD Distribución Electricidad: Reprocesar datos de energía para intentar reprocesar la información recogida e intentar que la indexe HA.

También has de tener en cuenta que tal y como se indica en la información, debido a limitaciones en la API que se utiliza para descargar los datos desde UFD (La cual ahora mismo tienen una incidencia con la importación de nuevas lecturas desde los contadores) va descargando los registros de los 2 años previos poco a poco para evitar bloqueos por sobredemanda.

**Comment by driosalido** [comment]
El problema es ese justo que indicas, pero me temo que esperar no va a ser la solución, ya que instalé la integración hace ya unos cuantos días y no tengo las estadísticas. Las consultas al api van bien ya que tengo descargada información ya desde 2022. 

```
user_files # head -2 billing_periods.csv
start_date,end_date,total_cost,power_cost,energy_cost,rent_cost,tax_cost,total_consumption
2022-07-11,2022-08-10,166.62,10.85,146.22,0.83,8.719999999999999,431.7569999999998

user_files # head -2 energy_data.csv
date,timestamp,consumption,price
01/07/2022 00,1656626400,0.271,0.29296
```

He probado varias veces el servicio de reprocesado de datos y estadísticas y nada. Imposible seleccionar el componente dentro del dashboard de energia :(

**Comment by driosalido** [comment]
Me desmiento a mi mismo. Ha sido volver a mirar y ya estaban las estadísticas... creo que han sido 3 dias de espera hasta que han aparecido 😄 

No se muy bien cual ha podido ser el problema para que haya tardado tanto.

Cierro la incidencia
